[platformio]
src_dir = .

[env:r4bb1t_fhc]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Configuração de partições (No OTA: ~2MB APP, ~2MB SPIFFS)
board_build.partitions = no_ota.csv

; Define a pasta atual como raiz do código fonte para não precisar de uma pasta src/
build_src_filter = +<*> -<.git/> -<nRF24_jammer/> -<CC1101_PinTest/> -<data/> -<fotos-fhc/>

; Bibliotecas necessárias (baixa automaticamente)
lib_deps = 
    bodmer/TFT_eSPI
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
    nrf24/RF24
    lsatan/SmartRC-CC1101-Driver-Lib
    sui77/rc-switch
    WiFi
    SPI
    FS
    SPIFFS
    Preferences
    EEPROM
    Update
    DNSServer
    WebServer

; Força o analisador de dependências do PlatformIO a varrer profundamente
lib_ldf_mode = deep

; Configurações da TFT_eSPI diretamente no build_flags 
; para não precisar editar o User_Setup.h da biblioteca
build_flags = 
    -Wl,-z,muldefs
    -D USER_SETUP_LOADED=1
    -D ST7735_DRIVER=1
    -D TFT_WIDTH=131
    -D TFT_HEIGHT=162
    -D TFT_RGB_ORDER=TFT_RGB
    -D ST7735_REDTAB=1
    -D TFT_MISO=-1
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_CS=5
    -D TFT_DC=17
    -D TFT_RST=16
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D LOAD_FONT6=1
    -D LOAD_FONT7=1
    -D LOAD_FONT8=1
    -D LOAD_GFXFF=1
    -D SMOOTH_FONT=1
    -D SPI_FREQUENCY=27000000
    -D CGRAM_OFFSET=1
    -D TFT_X_OFFSET=-50
    -D TFT_Y_OFFSET=0
    -D DISABLE_ALL_LIBRARY_WARNINGS=1
